/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.dsa_act2c;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class RPSHEALTH extends javax.swing.JFrame {
    int ph1 = 5;
    int ph2 = 5;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RPSHEALTH.class.getName());

    /**
     * Creates new form RPSHEALTH
     */
    public RPSHEALTH() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p1 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        p1.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        p1.setText("PLAYER 1");

        p2.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        p2.setText("PLAYER 2");

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel3.setText("[3] = SCISSOR");

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel4.setText("ROCK  PAPER SCISSOR BATTLE");

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel5.setText("[2] = PAPER");

        btn1.setFont(new java.awt.Font("Goudy Stout", 0, 12)); // NOI18N
        btn1.setText("ENTER");
        btn1.addActionListener(this::btn1ActionPerformed);

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel6.setText("[1] = ROCK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(p1)
                        .addGap(102, 102, 102)
                        .addComponent(p2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel3)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 32, Short.MAX_VALUE)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(230, 250, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p1)
                    .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(157, Short.MAX_VALUE)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 113, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        int p1 = Integer.parseInt(txt1.getText());
        int p2 = Integer.parseInt(txt2.getText());

        // Check if game is already over
        if (ph1 <= 0 || ph2 <= 0) {
            return;
        }

        // Draw
        if (p1 == p2) {
            JOptionPane.showMessageDialog(rootPane,
                "DRAW!\n\nPlayer 1 Health: " + ph1
                + "\nPlayer 2 Health: " + ph2,
                "RPS",
                JOptionPane.INFORMATION_MESSAGE);
        } // Paper vs Rock - Player 1 wins
        else if (p1 == 1 && p2 == 2) {
            ph2--;

            if (ph2 == 0) {
                JOptionPane.showMessageDialog(rootPane,
                    "PLAYER 1 WINS THE GAME!",
                    "GAME OVER",
                    JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(rootPane,
                    "Player 1 wins!\n\nPlayer 1 Health: " + ph1
                    + "\nPlayer 2 Health: " + ph2,
                    "RPS",
                    JOptionPane.INFORMATION_MESSAGE);
            }
        } // Paper vs Scissor - Player 2 wins
        else if (p1 == 1 && p2 == 3) {
            ph1--;

            if (ph1 == 0) {
                JOptionPane.showMessageDialog(rootPane,
                    "PLAYER 2 WINS THE GAME!",
                    "GAME OVER",
                    JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(rootPane,
                    "Player 2 wins!\n\nPlayer 1 Health: " + ph1
                    + "\nPlayer 2 Health: " + ph2,
                    "RPS",
                    JOptionPane.INFORMATION_MESSAGE);
            }
        } // Rock vs Paper - Player 2 wins
        else if (p1 == 2 && p2 == 1) {
            ph1--;

            if (ph1 == 0) {
                JOptionPane.showMessageDialog(rootPane,
                    "PLAYER 2 WINS THE GAME!",
                    "GAME OVER",
                    JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(rootPane,
                    "Player 2 wins!\n\nPlayer 1 Health: " + ph1
                    + "\nPlayer 2 Health: " + ph2,
                    "RPS",
                    JOptionPane.INFORMATION_MESSAGE);
            }
        } // Rock vs Scissor - Player 1 wins
        else if (p1 == 2 && p2 == 3) {
            ph2--;

            if (ph2 == 0) {
                JOptionPane.showMessageDialog(rootPane,
                    "PLAYER 1 WINS THE GAME!",
                    "GAME OVER",
                    JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(rootPane,
                    "Player 1 wins!\n\nPlayer 1 Health: " + ph1
                    + "\nPlayer 2 Health: " + ph2,
                    "RPS",
                    JOptionPane.INFORMATION_MESSAGE);
            }
        } // Scissor vs Paper - Player 1 wins
        else if (p1 == 3 && p2 == 1) {
            ph2--;

            if (ph2 == 0) {
                JOptionPane.showMessageDialog(rootPane,
                    "PLAYER 1 WINS THE GAME!",
                    "GAME OVER",
                    JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(rootPane,
                    "Player 1 wins!\n\nPlayer 1 Health: " + ph1
                    + "\nPlayer 2 Health: " + ph2,
                    "RPS",
                    JOptionPane.INFORMATION_MESSAGE);
            }
        } // Scissor vs Rock - Player 2 wins
        else if (p1 == 3 && p2 == 2) {
            ph1--;

            if (ph1 == 0) {
                JOptionPane.showMessageDialog(rootPane,
                    "PLAYER 2 WINS THE GAME!",
                    "GAME OVER",
                    JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(rootPane,
                    "Player 2 wins!\n\nPlayer 1 Health: " + ph1
                    + "\nPlayer 2 Health: " + ph2,
                    "RPS",
                    JOptionPane.INFORMATION_MESSAGE);
            }
        } // Invalid input
        else {
            JOptionPane.showMessageDialog(rootPane,
                "Invalid Input!\nPlease enter 1, 2, or 3.",
                "RPS",
                JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RPSHEALTH().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    // End of variables declaration//GEN-END:variables
}
